"""
Chat API routes.

Handles question answering with both synchronous and
streaming (SSE) response modes.
"""

import json
import logging

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse

from app.api.dependencies import get_qa_service
from app.api.schemas import ChatRequest, ChatResponse, ErrorResponse, SourceInfo
from app.services.qa_service import QAService

logger = logging.getLogger(__name__)

router = APIRouter(tags=["Chat"])


@router.post(
    "/chat",
    response_model=ChatResponse,
    responses={
        400: {"model": ErrorResponse},
        404: {"model": ErrorResponse},
    },
    summary="Ask a question",
    description="Ask a question about an uploaded document.",
)
async def chat(
    request: ChatRequest,
    qa_service: QAService = Depends(get_qa_service),
) -> ChatResponse:
    """
    Answer a question using the RAG pipeline.

    Retrieves relevant chunks from the document and generates
    a grounded answer using the LLM.
    """
    if not request.question.strip():
        raise HTTPException(status_code=400, detail="Question cannot be empty.")

    try:
        result = await qa_service.answer(
            document_id=request.document_id,
            question=request.question,
            session_id=request.session_id,
        )
    except KeyError:
        raise HTTPException(
            status_code=404,
            detail=f"Document not found: {request.document_id}",
        )
    except RuntimeError as exc:
        logger.error(f"QA failed: {exc}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail="An error occurred while generating the answer.",
        )

    sources = [
        SourceInfo(
            page=r.chunk.page_number,
            chunk=r.chunk.chunk_index,
            score=round(r.score, 4),
            preview=r.chunk.content[:150] + "...",
        )
        for r in result.sources
    ]

    return ChatResponse(
        answer=result.answer,
        sources=sources,
        suggested_questions=result.suggested_questions,
        session_id=request.session_id,
    )


@router.post(
    "/chat/stream",
    responses={
        400: {"model": ErrorResponse},
        404: {"model": ErrorResponse},
    },
    summary="Ask a question (streaming)",
    description="Ask a question with streaming token responses via SSE.",
)
async def chat_stream(
    request: ChatRequest,
    qa_service: QAService = Depends(get_qa_service),
) -> StreamingResponse:
    """
    Stream an answer using Server-Sent Events (SSE).

    Returns tokens as they are generated by the LLM,
    along with source citations and follow-up suggestions.
    """
    if not request.question.strip():
        raise HTTPException(status_code=400, detail="Question cannot be empty.")

    async def event_generator():
        """Generate SSE events from the QA service."""
        try:
            async for event in qa_service.answer_stream(
                document_id=request.document_id,
                question=request.question,
                session_id=request.session_id,
            ):
                event_type = event["type"]
                data = event["data"]

                if isinstance(data, (dict, list)):
                    data_str = json.dumps(data)
                else:
                    data_str = str(data)

                yield f"event: {event_type}\ndata: {data_str}\n\n"

        except Exception as exc:
            logger.error(f"Stream error: {exc}", exc_info=True)
            error_data = json.dumps({"error": str(exc)})
            yield f"event: error\ndata: {error_data}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )
